name: Build and Deploy Sphinx Documentation to Wiki

on:
  push:
    branches:
      - main  # Passe den Branch-Namen an, falls du einen anderen verwendest.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build Sphinx documentation
      run: |
        cd docs
        make html

    - name: Ensure build directory exists
      run: |
        if [ ! -d "docs/build/html" ]; then
          echo "Build directory does not exist"
          exit 1
        fi

    - name: Check build directory content
      run: ls -la docs/build/html/

    - name: Deploy to GitHub Wiki
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git wiki
        rm -rf wiki/*
        cp -r docs/build/html/* wiki/
        cd wiki
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update documentation"
        git push
